### ISSUE TITLE
IDLF as a library

### ISSUE THREAD

**Issue by nudles** [01org/idlf#5]
Since IDLF may have done much optimization for convolution/pooling/etc operations, can we use IDLF as a library?
If yes, how can we call the convolution::foward and convolution::backward functions, i.e., the API?
Thanks.

**Comment by jdukat** [comment]
Yes, it can be used as a library. Please note though that the project is now end of life, no quality is guaranteed and bugs will not be fixed.

**Comment by nudles** [comment]
Do you have documentations for that?
Or can you give me one example of calling the convolution functions.

Thanks.

**Comment by jdukat** [comment]
Samples are in the repository. Docs only in header files + samples.

**Comment by nudles** [comment]
Can you give me links to the files containing the samples?
Thank you.

**Comment by jdukat** [comment]
https://github.com/01org/idlf/tree/master/demo
